version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: sl-portfolio-prod
    ports:
      - "3001:80"  # Use port 3001 for this project
    environment:
      - NODE_ENV=production
      - VITE_GITHUB_TOKEN=${VITE_GITHUB_TOKEN}
      - VITE_GITHUB_USERNAME=${VITE_GITHUB_USERNAME}
      - VITE_GITHUB_EXCLUDE_REPOS=${VITE_GITHUB_EXCLUDE_REPOS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`stavlobel.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    networks:
      - web
      - portfolio-network
    volumes:
      - portfolio-logs:/var/log/nginx

  # Optional: Add a simple monitoring service
  watchtower:
    image: containrrr/watchtower
    container_name: portfolio-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Check every hour
      - WATCHTOWER_INCLUDE_STOPPED=true
    restart: unless-stopped
    networks:
      - portfolio-network

volumes:
  portfolio-logs:
    driver: local

networks:
  portfolio-network:
    driver: bridge
  web:
    external: true  # Shared network for reverse proxy 